version: "3.9"
services:
  frontend: 
    build: frontend/.
    ports:
      - 5173:5173
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - frontend/.env
  backend:
    build: backend/.
    ports:
      - 5000:5000
    container_name: backend
    env_file:
      - backend/.env